services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: golf-club:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/golf
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - mysql
    entrypoint: >
      sh -c "sleep 10 && java -jar app.jar"
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: golf
    ports:
      - "3307:3306"